# Generated by Django 5.2.6 on 2025-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='call_for_papers',
            field=models.FileField(blank=True, help_text='Upload PDF call for papers', null=True, upload_to='conference_pdfs/'),
        ),
    ]
